### ISSUE TITLE
Excuses Checklist

### ISSUE THREAD

**Issue by cwithac** [cwithac/excuses_app_api#15]
** Moved to Notes Tracker

- [x] Create
- [x] Read
- [x] Update
- [x] Delete

CREATE
- [x] Default count on create is 1. User does not create count.
- [x] Ability to cancel add form popup.
- [x] Blank occasion issue.

READ 
- [x] Shows relation between excuse and occasion. 
- [x] Sort by occasion alpha for full list.
- [x] Get occasions via $scope.
- [ ] **Clarify + for user.
- [x] Hidden while user is not logged in.

UPDATE
- [x] Edit form appears only on selected item, not all.
- [x] Edit count on click of + .
- [x] Count edit persists in PUT.
- [x] Ability to cancel edit form popup.
- [x] Hidden while user is not logged in.

DELETE
- [x] Destroy relations removes from /excuses backend.
- [x] Hidden while user is not logged in.

CSS 
- [ ] **Tags for occasions.

USER
- [x] Connect excuses to user.
- [x] C on excuses only works for logged in / user specific.
- [x] **U on excuses only works for logged in / user specific.
- [x] COUNT when not logged in? 
- [x] **D on excuses only works for logged in / user specific.

**Comment by cwithac** [comment]
Incomplete items moved to 'Notes for Monday' on Front End Repo.
